config/routes.rb
Rails.application.routes.draw do

  resources :age_groups, :schools, except: [:index, :show]
  resources :centers, except: [:show]
  resources :programs, except: [:index]
  get 'programs' => 'programs#index', defaults: { format: :json }

  post 'profilum/login' => 'profilum#login', as: :profilum_login

  namespace :admin do
    resources :age_groups, only: [:index, :show] do
      member do
        post 'priority', defaults: { format: :json }
      end
    end
    resources :centers, only: [:index, :show]
    resources :programs, only: [:index, :show] do
      member do
        post 'toggle', defaults: { format: :json }
        put 'age_groups/:age_group_id' => :add_age_group, as: :age_group, defaults: { format: :json }
        delete 'age_groups/:age_group_id' => :remove_age_group, defaults: { format: :json }
        put 'schools/:school_id' => :add_school, as: :school, defaults: { format: :json }
        delete 'schools/:school_id' => :remove_school, defaults: { format: :json }
      end
    end
    resources :program_clicks, only: [:index, :show]
    resources :schools, only: [:index, :show] do
      member do
        post 'toggle', defaults: { format: :json }
      end
    end
  end
end

app/models/program_click.rb
class ProgramClick < ApplicationRecord
  PER_PAGE = 25

  belongs_to :program, counter_cache: true
  belongs_to :agent, optional: true

  scope :since, ->(date) { where('date(created_at) >= date(?)', date.to_date) }
  scope :before, ->(date) { where('date(created_at) <= date(?)', date.to_date) }
  scope :today, -> { where('date(created_at) = date(now())') }
  scope :this_week, -> { since(1.week.ago).before(Time.now.to_date) }
  scope :this_month, -> { since(1.month.ago).before(Time.now.to_date) }

  # @param [Integer] page
  def self.page_for_administration(page = 1)
    order('id desc').page(page).per(PER_PAGE)
  end

  def name
    program.name
  end
end

app/controllers/admin/program_clicks_controller.rb
class Admin::ProgramClicksController < AdminController
  before_action :set_entity, except: [:index]

  # get /admin/program_clicks
  def index
    @collection = Program.with_clicks.page_for_administration(current_page)
  end

  # get /admin/program_clicks/:id
  def show
    @collection = @entity.program_clicks.page_for_administration(current_page)
  end

  private

  def restrict_access
    require_privilege :click_viewer
  end

  def set_entity
    @entity = Program.find_by(id: params[:id])
    if @entity.nil?
      handle_http_404('Cannot find program')
    end
  end
end

app/views/admin/program_clicks/_list.html.erb
<% if collection.any? %>
    <ul class="list-of-entities">
      <% collection.each do |entity| %>
          <li data-id="<%= entity.id %>">
            <%= render partial: "admin/program_clicks/entity/program", locals: { entity: entity } %>
          </li>
      <% end %>
    </ul>
<% else %>
    <div class="message-box-warning"><%= t('.no_programs') %></div>
<% end %>

app/views/admin/program_clicks/_nav_item.html.erb
<div>
  <%= link_to t('.text'), admin_program_clicks_path %>
</div>
<div class="description">
  <%= t('.description') %>
</div>

app/views/admin/program_clicks/index.html.erb
<% content_for :meta_title, t('.title', page: current_page) %>
<% content_for :breadcrumbs do %>
    <span><%= t('admin.program_clicks.nav_item.text') %></span>
<% end %>

<article class="entity-page">
  <h1><%= t('.heading') %></h1>

  <ul class="actions">
    <li><%= back_icon(admin_path) %></li>
  </ul>

  <%= paginate @collection %>
  <%= render partial: 'list', locals: { collection: @collection } %>
  <%= paginate @collection %>
</article>

app/views/admin/program_clicks/show.html.erb
<% content_for :meta_title, t('.title', name: @entity.name, page: current_page) %>
<% content_for :breadcrumbs do %>
    <%= link_to(t('admin.program_clicks.nav_item.text'), admin_program_clicks_path) %>
    <span><%= @entity.name %></span>
<% end %>

<article>
  <h1><%= t('.heading', name: @entity.name) %></h1>

  <ul class="actions">
    <li><%= return_icon(admin_program_clicks_path) %></li>
  </ul>

  <ul>
    <li>
      <%= t('click_period.today') %>
      <%= t(:program_click_count, count: @entity.click_count(:day)) %>
    </li>
    <li>
      <%= t('click_period.this_week') %>
      <%= t(:program_click_count, count: @entity.click_count(:week)) %>
    </li>
    <li>
      <%= t('click_period.this_month') %>
      <%= t(:program_click_count, count: @entity.click_count(:month)) %>
    </li>
  </ul>

  <%= paginate @collection %>
  <%= render partial: 'shared/admin/list', locals: { collection: @collection } %>
  <%= paginate @collection %>
</article>