config/routes.rb
Rails.application.routes.draw do

  resources :age_groups, :schools, except: [:index, :show]
  resources :centers, except: [:show]
  resources :programs, except: [:index]
  get 'programs' => 'programs#index', defaults: { format: :json }

  post 'profilum/login' => 'profilum#login', as: :profilum_login

  namespace :admin do
    resources :age_groups, only: [:index, :show] do
      member do
        post 'priority', defaults: { format: :json }
      end
    end
    resources :centers, only: [:index, :show]
    resources :programs, only: [:index, :show] do
      member do
        post 'toggle', defaults: { format: :json }
        put 'age_groups/:age_group_id' => :add_age_group, as: :age_group, defaults: { format: :json }
        delete 'age_groups/:age_group_id' => :remove_age_group, defaults: { format: :json }
        put 'schools/:school_id' => :add_school, as: :school, defaults: { format: :json }
        delete 'schools/:school_id' => :remove_school, defaults: { format: :json }
      end
    end
    resources :program_clicks, only: [:index, :show]
    resources :schools, only: [:index, :show] do
      member do
        post 'toggle', defaults: { format: :json }
      end
    end
  end
end

app/models/program.rb
class Program < ApplicationRecord
  include Toggleable

  PER_PAGE     = 20
  NAME_LIMIT   = 255
  SLUG_LIMIT   = 255
  LEAD_LIMIT   = 255
  URL_LIMIT    = 255
  PRICE_RANGE  = (0..16777215)
  SLUG_PATTERN = /\A[a-z0-9]+[-a-z0-9_]{,248}[a-z0-9]+\z/

  toggleable :visible, :use_discount

  mount_uploader :image, ProgramImageUploader

  belongs_to :center, counter_cache: true
  has_many :program_clicks, dependent: :destroy
  has_many :program_age_groups, dependent: :destroy
  has_many :program_schools, dependent: :destroy
  has_many :age_groups, through: :program_age_groups
  has_many :schools, through: :program_schools

  validates_presence_of :name, :url
  validates_length_of :name, maximum: NAME_LIMIT
  validates_length_of :slug, maximum: SLUG_LIMIT
  validates_format_of :slug, with: SLUG_PATTERN, allow_blank: true
  validates_length_of :lead, maximum: LEAD_LIMIT
  validates_length_of :url, maximum: URL_LIMIT
  validates_inclusion_of :price, in: PRICE_RANGE
  validates_inclusion_of :old_price, in: PRICE_RANGE, allow_nil: true
  validate :old_price_should_be_meaningful

  scope :ordered_by_name, -> { order('name asc') }
  scope :ordered_by_price, -> { order('price asc, name asc') }
  scope :visible, -> { where(visible: true) }
  scope :with_school_ids, ->(ids) { joins(:program_schools).where(program_schools: { school_id: ids }) unless ids.blank? }
  scope :with_age_group_ids, ->(ids) { joins(:program_age_groups).where(program_age_groups: { age_group_id: ids }) unless ids.blank? }
  scope :near_stations, ->(ids) { where(center_id: Center.near_stations(ids).pluck(:id)) unless ids.blank? }
  scope :price_from, ->(value) { where('price >= ?', value.to_i) unless value.blank? }
  scope :price_to, ->(value) { where('price <= ?', value.to_i) unless value.blank? }
  scope :filtered, ->(f) { with_school_ids(f[:school]).with_age_group_ids(f[:age_group]).price_from(f[:price_from]).price_to(f[:price_to]).near_stations(f[:subway_station]) }
  scope :with_clicks, -> { where('program_clicks_count > 0') }

  # @param [Integer] page
  def self.page_for_administration(page)
    ordered_by_name.page(page).per(PER_PAGE)
  end

  # @param [Integer] page
  # @param [Hash] filter
  def self.page_for_visitors(page = 1, filter = {})
    filtered(filter).visible.ordered_by_price.distinct.page(page).per(9)
  end

  def self.entity_parameters
    %i(center_id image name lead url price old_price visible use_discount)
  end

  def self.prices
    min_price = visible.minimum(:price).to_i
    max_price = visible.maximum(:price).to_i
    (min_price..max_price)
  end

  # @param [Boolean] force
  def discount(force = false)
    return 0 if old_price.to_i < 1
    (use_discount? || force) ? (old_price - price) : 0
  end

  def discount_percent
    return 0 if old_price.to_i < 1

    ((1 - price.to_f/old_price.to_f) * 100).round.to_i
  end

  def ages
    age_groups.ordered_by_priority.map(&:name).join(' ')
  end

  # @param [Symbol] period
  def click_count(period)
    case period.to_sym
      when :week
        program_clicks.this_week.count
      when :month
        program_clicks.this_month.count
      else
        program_clicks.today.count
    end
  end

  private

  def old_price_should_be_meaningful
    return if old_price.to_i < 1
    error = I18n.t('activerecord.errors.models.programs.attributes.old_price.should_be_greater_than_price')
    if old_price <= price
      errors.add(:old_price, error)
    end
  end
end

app/controllers/admin/programs_controller.rb
class Admin::ProgramsController < AdminController
  include ToggleableEntity

  before_action :set_entity, except: [:index]

  # get /admin/programs
  def index
    @collection = Program.page_for_administration(current_page)
  end

  # get /admin/programs/:id
  def show
  end

  # put /admin/programs/:id/age_groups/:age_group_id
  def add_age_group
    @entity.program_age_groups.create(age_group_id: params[:age_group_id])

    head :no_content
  end

  # delete /admin/programs/:id/age_groups/:age_group_id
  def remove_age_group
    @entity.program_age_groups.where(age_group_id: params[:age_group_id]).destroy_all

    head :no_content
  end

  # put /admin/programs/:id/schools/:school_id
  def add_school
    @entity.program_schools.create(school_id: params[:school_id])

    head :no_content
  end

  # delete /admin/programs/:id/schools/:school_id
  def remove_school
    @entity.program_schools.where(school_id: params[:school_id]).destroy_all

    head :no_content
  end

  protected

  def restrict_access
    require_privilege :program_manager
  end

  def set_entity
    @entity = Program.find_by(id: params[:id])
    if @entity.nil?
      handle_http_404('Cannot find program')
    end
  end
end

app/controllers/programs_controller.rb
class ProgramsController < AdminController
  before_action :set_entity, only: [:show, :edit, :update, :destroy]
  skip_before_action :restrict_access, only: [:index, :show]

  # get /programs
  def index
    @filter = params[:filter] || Hash.new
    @collection = Program.page_for_visitors(current_page, @filter)
  end

  # get /programs/new
  def new
    @entity = Program.new
  end

  # get /programs/:id
  def show
    @entity.program_clicks.create(tracking_for_entity)
    redirect_to @entity.url
  end

  # post /programs
  def create
    @entity = Program.new(entity_parameters)
    if @entity.save
      redirect_to admin_program_path(@entity.id)
    else
      render :new, status: :bad_request
    end
  end

  # get /programs/:id/edit
  def edit
  end

  # patch /programs/:id
  def update
    if @entity.update(entity_parameters)
      redirect_to admin_program_path(@entity.id), notice: t('programs.update.success')
    else
      render :edit, status: :bad_request
    end
  end

  # delete /programs/:id
  def destroy
    if @entity.destroy
      flash[:notice] = t('programs.destroy.success')
    end
    redirect_to admin_programs_path
  end

  private

  def restrict_access
    require_privilege :program_manager
  end

  def set_entity
    @entity = Program.find_by(id: params[:id])
    if @entity.nil?
      handle_http_404('Cannot find program')
    end
  end

  def entity_parameters
    params.require(:program).permit(Program.entity_parameters)
  end
end

app/helpers/programs_helper.rb
module ProgramsHelper
  # @param [AgeGroup] entity
  def admin_age_group_link(entity)
    link_to(entity.name, admin_age_group_path(entity.id))
  end

  # @param [Center] entity
  def admin_center_link(entity)
    link_to(entity.name, admin_center_path(entity.id))
  end

  # @param [Program] entity
  def admin_program_link(entity)
    link_to(entity.name, admin_program_path(entity.id))
  end

  # @param [Program] entity
  def admin_program_click_link(entity)
    link_to(entity.name, admin_program_click_path(entity.id))
  end

  # @param [School] entity
  def admin_school_link(entity)
    link_to(entity.name, admin_school_path(entity.id))
  end

  # @param [Program] entity
  def program_link(entity, text = entity.name, options = {})
    html_options = { target: '_blank' }.merge(options)
    link_to(text, program_path(entity.id), html_options)
  end

  def centers_for_select
    Center.ordered_by_name.map { |c| [c.name, c.id] }
  end

  # @param [Center] entity
  def center_image_preview(entity)
    return '' if entity.image.blank?
    versions = "#{entity.image.preview_2x.url} 2x"
    image_tag(entity.image.preview.url, alt: entity.name, srcset: versions)
  end

  # @param [Program] entity
  def program_image_preview(entity)
    return '' if entity.image.blank?
    versions = "#{entity.image.preview_2x.url} 2x"
    image_tag(entity.image.preview.url, alt: entity.name, srcset: versions)
  end

  # @param [Program] entity
  def program_image_medium(entity)
    return '' if entity.image.blank?
    versions = "#{entity.image.medium_2x.url} 2x"
    image_tag(entity.image.medium.url, alt: entity.name, srcset: versions)
  end

  # @param [Program] entity
  def program_image_small(entity)
    return '' if entity.image.blank?
    versions = "#{entity.image.medium.url} 2x"
    image_tag(entity.image.small.url, alt: entity.name, srcset: versions)
  end
end

app/views/admin/programs/_nav_item.html.erb
<div>
  <%= link_to t('.text'), admin_programs_path %>
</div>
<div class="description">
  <%= t('.description') %>
</div>

app/views/admin/programs/_toggleable.html.erb
<div class="toggleable" data-url="<%= toggle_admin_program_path(entity) %>">
  <% Program.toggleable_attributes.each do |flag| %>
  <span class="<%= entity.attributes[flag.to_s] ? 'active' : 'inactive' %>" data-flag="<%= flag %>">
    <%= t("activerecord.attributes.program.#{flag}") %>
  </span>
  <% end %>
</div>

app/views/admin/programs/index.html.erb
<% content_for :meta_title, t('.title', page: current_page) %>
<% content_for :breadcrumbs do %>
    <span><%= t('admin.programs.nav_item.text') %></span>
<% end %>

<article class="entity-page">
  <h1><%= t('.heading') %></h1>

  <ul class="actions">
    <li><%= back_icon(admin_path) %></li>
    <li><%= create_icon(new_program_path) %></li>
  </ul>

  <%= paginate @collection %>
  <%= render partial: 'shared/admin/list', locals: { collection: @collection } %>
  <%= paginate @collection %>
</article>

app/views/admin/programs/show.html.erb
<% content_for :meta_title, t('.title', name: @entity.name) %>
<% content_for :breadcrumbs do %>
    <%= link_to(t('admin.programs.nav_item.text'), admin_programs_path) %>
    <span><%= @entity.name %></span>
<% end %>

<article>
  <h1><%= @entity.name %></h1>

  <ul class="actions">
    <li><%= back_icon(admin_programs_path) %></li>
    <li><%= edit_icon(edit_program_path(@entity.id)) %></li>
  </ul>

  <% unless @entity.image.blank? %>
      <figure>
        <%= program_image_medium(@entity) %>
        <figcaption>
          <%= t('activerecord.attributes.program.image') %>
        </figcaption>
      </figure>
  <% end %>

  <dl>
    <dt><%= t('activerecord.attributes.program.center') %></dt>
    <dd>
      <%= admin_center_link(@entity.center) %>
    </dd>

    <dt><%= t('activerecord.attributes.program.url') %></dt>
    <dd>
      <%= link_to(@entity.url, @entity.url, target: '_blank') %>
    </dd>

    <dt><%= t('activerecord.attributes.program.lead') %></dt>
    <dd>
      <%= @entity.lead %>
    </dd>

    <dt><%= t('activerecord.attributes.program.ages') %></dt>
    <% AgeGroup.page_for_administration.each do |age_group| %>
        <dd data-url="<%= age_group_admin_program_path(id: @entity.id, age_group_id: age_group.id) %>" class="program-age-group">
          <% element_id = "age_group_#{age_group.id}" %>
          <%= check_box_tag "program_age_group[#{age_group.id}]", age_group.id, age_group.has_program?(@entity), id: element_id %>
          <%= label_tag element_id, age_group.name %>
        </dd>
    <% end %>

    <dt><%= t('activerecord.attributes.program.price') %></dt>
    <dd>
      <%= @entity.price %>
    </dd>

    <% if @entity.old_price.to_i > 0 %>
        <dt><%= t('activerecord.attributes.program.old_price') %></dt>
        <dd>
          <%= @entity.old_price %>
        </dd>

        <dt><%= t('activerecord.attributes.program.discount') %></dt>
        <dd>
          <%= @entity.discount(true) %>
        </dd>
    <% end %>

    <dt><%= t('activerecord.attributes.program_school.school') %></dt>
    <dd class="program-school">
      <ul>
        <% School.ordered_by_name.each do |school| %>
            <li data-url="<%= school_admin_program_path(id: @entity.id, school_id: school.id) %>">
              <% element_id = "school_#{school.id}" %>
              <%= check_box_tag "program_school[#{school.id}]", school.id, school.has_program?(@entity), id: element_id %>
              <%= label_tag element_id, school.name %>
            </li>
        <% end %>
      </ul>
    </dd>
  </dl>

  <%= render partial: 'admin/programs/toggleable', locals: { entity: @entity } %>
</article>

<script>
    'use strict';

    $(function() {
        $('.program-age-group, .program-school').find('input[type=checkbox]').on('click', function() {
            let url = $(this).parent().data('url');
            let method = $(this).is(':checked') ? 'PUT' : 'DELETE';

            $.ajax(url, {
                method: method
            }).fail(handle_ajax_failure);
        });
    });
</script>