config/routes.rb
Rails.application.routes.draw do

  resources :age_groups, :schools, except: [:index, :show]
  resources :centers, except: [:show]
  resources :programs, except: [:index]
  get 'programs' => 'programs#index', defaults: { format: :json }

  post 'profilum/login' => 'profilum#login', as: :profilum_login

  namespace :admin do
    resources :age_groups, only: [:index, :show] do
      member do
        post 'priority', defaults: { format: :json }
      end
    end
    resources :centers, only: [:index, :show]
    resources :programs, only: [:index, :show] do
      member do
        post 'toggle', defaults: { format: :json }
        put 'age_groups/:age_group_id' => :add_age_group, as: :age_group, defaults: { format: :json }
        delete 'age_groups/:age_group_id' => :remove_age_group, defaults: { format: :json }
        put 'schools/:school_id' => :add_school, as: :school, defaults: { format: :json }
        delete 'schools/:school_id' => :remove_school, defaults: { format: :json }
      end
    end
    resources :program_clicks, only: [:index, :show]
    resources :schools, only: [:index, :show] do
      member do
        post 'toggle', defaults: { format: :json }
      end
    end
  end
end

app/models/age_group.rb
class AgeGroup < ApplicationRecord
  include RequiredUniqueName

  NAME_LIMIT     = 10
  PRIORITY_RANGE = (1..32767)

  has_many :program_age_groups, dependent: :destroy
  has_many :programs, through: :program_age_groups

  after_initialize :set_next_priority

  before_validation :normalize_priority

  validates_length_of :name, maximum: NAME_LIMIT

  scope :ordered_by_priority, -> { order('priority asc, name asc') }
  scope :with_programs, -> { joins(:program_age_groups).where(program_age_groups: { program_id: Program.visible.pluck(:id) }) }

  def self.page_for_administration
    ordered_by_priority
  end

  def self.list_for_visitors
    with_programs.ordered_by_priority.uniq
  end

  def self.entity_parameters
    %i(name)
  end

  # @param [Program] program
  def has_program?(program)
    program_age_groups.where(program: program).exists?
  end

  private

  def set_next_priority
    if id.nil? && priority == 1
      self.priority = self.class.maximum(:priority).to_i + 1
    end
  end

  def normalize_priority
    self.priority = PRIORITY_RANGE.first if priority < PRIORITY_RANGE.first
    self.priority = PRIORITY_RANGE.last if priority > PRIORITY_RANGE.last
  end
end

app/controllers/admin/age_groups_controller.rb
class Admin::AgeGroupsController < AdminController
  include EntityPriority

  before_action :set_entity, except: [:index]

  # get /admin/age_groups
  def index
    @collection = AgeGroup.page_for_administration
  end

  # get /admin/age_groups/:id
  def show
  end

  protected

  def restrict_access
    require_privilege :program_manager
  end

  def set_entity
    @entity = AgeGroup.find_by(id: params[:id])
    if @entity.nil?
      handle_http_404('Cannot find age_group')
    end
  end
end

app/controllers/age_groups_controller.rb
class AgeGroupsController < AdminController
  before_action :set_entity, only: [:edit, :update, :destroy]

  # get /age_groups/new
  def new
    @entity = AgeGroup.new
  end

  # post /age_groups
  def create
    @entity = AgeGroup.new(entity_parameters)
    if @entity.save
      redirect_to admin_age_group_path(@entity.id)
    else
      render :new, status: :bad_request
    end
  end

  # get /age_groups/:id/edit
  def edit
  end

  # patch /age_groups/:id
  def update
    if @entity.update(entity_parameters)
      redirect_to admin_age_group_path(@entity.id), notice: t('age_groups.update.success')
    else
      render :edit, status: :bad_request
    end
  end

  # delete /age_groups/:id
  def destroy
    if @entity.destroy
      flash[:notice] = t('age_groups.destroy.success')
    end
    redirect_to admin_age_groups_path
  end

  private

  def restrict_access
    require_privilege :program_manager
  end

  def set_entity
    @entity = AgeGroup.find_by(id: params[:id])
    if @entity.nil?
      handle_http_404('Cannot find age_group')
    end
  end

  def entity_parameters
    params.require(:age_group).permit(AgeGroup.entity_parameters)
  end
end

app/views/admin/age_groups/_nav_item.html.erb
<div>
  <%= link_to t('.text'), admin_age_groups_path %>
</div>
<div class="description">
  <%= t('.description') %>
</div>

app/views/admin/age_groups/index.html.erb
<% content_for :meta_title, t('.title') %>
<% content_for :breadcrumbs do %>
    <span><%= t('admin.age_groups.nav_item.text') %></span>
<% end %>

<article>
  <h1><%= t('.heading') %></h1>

  <ul class="actions">
    <li><%= back_icon(admin_path) %></li>
    <li><%= create_icon(new_age_group_path) %></li>
  </ul>

  <%= render partial: 'shared/admin/list_with_priority', locals: { collection: @collection } %>
</article>

app/views/admin/age_groups/show.html.erb
<% content_for :meta_title, t('.title', name: @entity.name) %>
<% content_for :breadcrumbs do %>
    <%= link_to(t('admin.age_groups.nav_item.text'), admin_age_groups_path) %>
    <span><%= @entity.name %></span>
<% end %>

<article class="entity-page">
  <h1><%= @entity.name %></h1>

  <ul class="actions">
    <li><%= back_icon(admin_age_groups_path) %></li>
    <li><%= edit_icon(edit_age_group_path(@entity.id)) %></li>
  </ul>

  <dl>
    <dt><%= t('activerecord.attributes.age_group.name') %></dt>
    <dd>
      <%= @entity.name %>
    </dd>
  </dl>

  <section>
    <h2><%= t(:program_count, count: @entity.programs_count) %></h2>

    <%= render partial: 'shared/admin/list', locals: { collection: @entity.programs.ordered_by_name } %>
  </section>
</article>