config/routes.rb
Rails.application.routes.draw do

  resources :age_groups, :schools, except: [:index, :show]
  resources :centers, except: [:show]
  resources :programs, except: [:index]
  get 'programs' => 'programs#index', defaults: { format: :json }

  post 'profilum/login' => 'profilum#login', as: :profilum_login

  namespace :admin do
    resources :age_groups, only: [:index, :show] do
      member do
        post 'priority', defaults: { format: :json }
      end
    end
    resources :centers, only: [:index, :show]
    resources :programs, only: [:index, :show] do
      member do
        post 'toggle', defaults: { format: :json }
        put 'age_groups/:age_group_id' => :add_age_group, as: :age_group, defaults: { format: :json }
        delete 'age_groups/:age_group_id' => :remove_age_group, defaults: { format: :json }
        put 'schools/:school_id' => :add_school, as: :school, defaults: { format: :json }
        delete 'schools/:school_id' => :remove_school, defaults: { format: :json }
      end
    end
    resources :program_clicks, only: [:index, :show]
    resources :schools, only: [:index, :show] do
      member do
        post 'toggle', defaults: { format: :json }
      end
    end
  end
end

app/models/center.rb
class Center < ApplicationRecord
  include RequiredUniqueName

  PER_PAGE = 20

  NAME_LIMIT   = 255
  SLUG_LIMIT   = 255
  PLACE_LIMIT  = 255
  URL_LIMIT    = 255
  SLUG_PATTERN = /\A[a-z0-9]+[-a-z0-9_]{,248}[a-z0-9]+\z/

  LATITUDE_RANGE  = (-90..90)
  LONGITUDE_RANGE = (-180..180)

  mount_uploader :image, CenterImageUploader

  has_many :programs, dependent: :destroy
  has_many :center_subway_stations, dependent: :destroy
  has_many :subway_stations, through: :center_subway_stations

  validates_presence_of :url
  validates_length_of :name, maximum: NAME_LIMIT
  validates_length_of :place, maximum: PLACE_LIMIT
  validates_length_of :slug, maximum: SLUG_LIMIT
  validates_format_of :slug, with: SLUG_PATTERN, allow_blank: true
  validates_length_of :url, maximum: URL_LIMIT
  validates_inclusion_of :latitude, in: LATITUDE_RANGE, allow_nil: true
  validates_inclusion_of :longitude, in: LONGITUDE_RANGE, allow_nil: true

  scope :with_programs, -> { joins(:programs).where(programs: { visible: true }) }
  scope :near_stations, ->(ids) { joins(:center_subway_stations).where(center_subway_stations: { subway_station_id: ids }) unless ids.blank? }

  # @param [Integer] page
  def self.page_for_administration(page = 1)
    ordered_by_name.page(page).per(PER_PAGE)
  end

  def self.list_for_visitors
    with_programs.ordered_by_name.uniq
  end

  def self.entity_parameters
    %i(name slug url place image latitude longitude)
  end

  def subway
    subway_stations.ordered_by_name.map(&:name).join(', ')
  end

  def coordinates
    return '' if latitude.nil? || longitude.nil?
    "#{latitude};#{longitude}"
  end
end

app/controllers/admin/centers_controller.rb
class Admin::CentersController < AdminController
  before_action :set_entity, except: [:index]

  # get /admin/centers
  def index
    @collection = Center.page_for_administration(current_page)
  end

  # get /admin/centers/:id
  def show
  end

  protected

  def restrict_access
    require_privilege :program_manager
  end

  def set_entity
    @entity = Center.find_by(id: params[:id])
    if @entity.nil?
      handle_http_404('Cannot find center')
    end
  end
end

app/controllers/centers_controller.rb
class CentersController < ApplicationController
  before_action :restrict_access, except: [:index]
  before_action :set_entity, only: [:edit, :update, :destroy]
  layout 'admin', except: [:index]

  # get /centers
  def index
    @collection = Center.list_for_visitors
  end

  # get /centers/new
  def new
    @entity = Center.new
  end

  # post /centers
  def create
    @entity = Center.new(entity_parameters)
    if @entity.save
      redirect_to admin_center_path(@entity.id)
    else
      render :new, status: :bad_request
    end
  end

  # get /centers/:id/edit
  def edit
  end

  # patch /centers/:id
  def update
    if @entity.update(entity_parameters)
      redirect_to admin_center_path(@entity.id), notice: t('centers.update.success')
    else
      render :edit, status: :bad_request
    end
  end

  # delete /centers/:id
  def destroy
    if @entity.destroy
      flash[:notice] = t('centers.destroy.success')
    end
    redirect_to admin_centers_path
  end

  private

  def restrict_access
    require_privilege :program_manager
  end

  def set_entity
    @entity = Center.find_by(id: params[:id])
    if @entity.nil?
      handle_http_404('Cannot find center')
    end
  end

  def entity_parameters
    params.require(:center).permit(Center.entity_parameters)
  end
end

app/views/admin/centers/_nav_item.html.erb
<div>
  <%= link_to t('.text'), admin_centers_path %>
</div>
<div class="description">
  <%= t('.description') %>
</div>

app/views/admin/centers/index.html.erb
<% content_for :meta_title, t('.title', page: current_page) %>
<% content_for :breadcrumbs do %>
    <span><%= t('admin.centers.nav_item.text') %></span>
<% end %>

<article class="entity-page">
  <h1><%= t('.heading') %></h1>

  <ul class="actions">
    <li><%= back_icon(admin_path) %></li>
    <li><%= create_icon(new_center_path) %></li>
  </ul>

  <%= paginate @collection %>
  <%= render partial: 'shared/admin/list', locals: { collection: @collection } %>
  <%= paginate @collection %>
</article>

app/views/admin/centers/show.html.erb
<% content_for :meta_title, t('.title', name: @entity.name) %>
<% content_for :breadcrumbs do %>
    <%= link_to(t('admin.centers.nav_item.text'), admin_centers_path) %>
    <span><%= @entity.name %></span>
<% end %>

<article class="entity-page">
  <h1><%= @entity.name %></h1>

  <ul class="actions">
    <li><%= back_icon(admin_centers_path) %></li>
    <li><%= edit_icon(edit_center_path(@entity.id)) %></li>
  </ul>

  <dl>
    <% unless @entity.image.blank? %>
        <dt><%= t('activerecord.attributes.center.image') %></dt>
        <dd>
          <figure><%= center_image_preview(@entity) %></figure>
        </dd>
    <% end %>

    <dt><%= t('activerecord.attributes.center.url') %></dt>
    <dd>
      <%= link_to(@entity.url, @entity.url, target: '_blank') %>
    </dd>

    <dt><%= t('activerecord.attributes.center.place') %></dt>
    <dd>
      <%= @entity.place %>
    </dd>

    <dt><%= t('activerecord.attributes.center.slug') %></dt>
    <dd>
      <%= @entity.slug %>
    </dd>

    <% unless @entity.latitude.nil? %>
        <dt><%= t('activerecord.attributes.center.latitude') %></dt>
        <dd><%= @entity.latitude %></dd>
    <% end %>

    <% unless @entity.longitude.nil? %>
        <dt><%= t('activerecord.attributes.center.longitude') %></dt>
        <dd><%= @entity.longitude %></dd>
    <% end %>
  </dl>

  <section>
    <h2><%= t('admin.programs.nav_item.text') %></h2>

    <%= render partial: 'shared/admin/list', locals: { collection: @entity.programs.ordered_by_name } %>
  </section>
</article>